"""create users table

Revision ID: b67ea6cda850
Revises: c4f00d9cdce6
Create Date: 2025-11-05 08:27:56.053443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b67ea6cda850'
down_revision: Union[str, Sequence[str], None] = 'c4f00d9cdce6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('streak', sa.Integer(), nullable=False),
    sa.Column('max_streak', sa.Integer(), nullable=False),
    sa.Column('frozen_days', sa.Integer(), nullable=False),
    sa.Column('last_checkin', sa.Date(), nullable=True),
    sa.Column('last_streak_reset', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
